### ISSUE TITLE
Up to date IXP parameters

### ISSUE THREAD

**Issue by William394873** [CAIDA/multilateral#2]
Dear,

Is there another up-to-date IXP parameter file? I got a lot of "-1" for summary file, and I also got a "KeyError: 'communities'" when running Inference function. 

Thanks!

**Comment by bhuffaker** [comment]
Unfortunately we are not maintain this code.  We do have a updated IXP dataset, but I don't think it includes the required communities. https://catalog.caida.org/details/dataset/ixps

**Comment by William394873** [comment]
Thanks! But is there another updated version of multilateral peering inference? I notice that CAIDA still update the serial-2 AS relationship every month. Does it still rely on BGP communities?

Best,

**Comment by bhuffaker** [comment]
Serial-2 is still using the old IXP file.  We are working on generating a new BGP communities file, but no timeline for when that might be finished.
